// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package models

// Developers defines model for Developers.
type Developers struct {
	HasNext *bool        `json:"hasNext,omitempty"`
	Items   *[]Developer `json:"items,omitempty"`
}

// Error defines model for Error.
type Error struct {

	// Human-readable error type, corresponds to HTTP status
	ErrorType *string `json:"errorType,omitempty"`

	// Human-readable description of the error
	Message *string `json:"message,omitempty"`
}

// Page defines model for Page.
type Page int

// PageSize defines model for PageSize.
type PageSize int

// Sort defines model for Sort.
type Sort string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse Error

// SearchDevelopersParams defines parameters for SearchDevelopers.
type SearchDevelopersParams struct {

	// Only return results whose name matches the value exactly
	Name *string `json:"name,omitempty"`

	// Only return results whose team matches the value exactly
	Team *string `json:"team,omitempty"`

	// The number of items to offset the results by
	Page *Page `json:"page,omitempty"`

	// The number of items to be returned in the response
	PageSize *PageSize `json:"pageSize,omitempty"`

	// Sort the results by the provided fields and direction, in format `<field name>:<direction>,...`
	// Where `<direction>` can be `asc` or `desc`
	Sort *Sort `json:"sort,omitempty"`
}

// CreateDeveloperJSONBody defines parameters for CreateDeveloper.
type CreateDeveloperJSONBody Developer

// UpdateDeveloperJSONBody defines parameters for UpdateDeveloper.
type UpdateDeveloperJSONBody Developer

// CreateDeveloperJSONRequestBody defines body for CreateDeveloper for application/json ContentType.
type CreateDeveloperJSONRequestBody CreateDeveloperJSONBody

// UpdateDeveloperJSONRequestBody defines body for UpdateDeveloper for application/json ContentType.
type UpdateDeveloperJSONRequestBody UpdateDeveloperJSONBody
